{% set name = "uf3" %}
{% set version = "0.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/uf3-{{ version }}.tar.gz
  sha256: 10b706822d217a6407ddac40bda54bce9ea56ffd78ef6ddbe687924a203fb893

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - ase
    - matplotlib-base
    - ndsplines
    - numba
    - numpy
    - pandas
    - plotly
    - pyyaml
    - scikit-learn
    - scipy
    - pytables
    - tqdm

test:
  imports:
    - uf3
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/uf3/uf3
  summary: Ultra-Fast Force Fields for molecular dynamics
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
